### ISSUE TITLE
Add Flowable support

### ISSUE THREAD

**Issue by aaloise** [zkoss-demo/rxzk#1]
Consider include support for Flowable, which is backpressure-enabled.

**Comment by scribetw** [comment]
Hi.

You can easily transform an `Observable` into a `Flowable` by calling `observable.toFlowable(BackpressureStrategy.XXX);`
http://reactivex.io/RxJava/javadoc/io/reactivex/Observable.html#toFlowable-io.reactivex.BackpressureStrategy-

That's why we didn't provide `ZkFlowable` by default.
